module.exports = {
  request_timeout: "clientTimeout",
  validation_error_token_is_required: "badData",
  validation_error_token_length_must_be_at_least_12_characters_long: "badData",
  validation_error_token_length_must_be_less_than_or_equal_to_30_characters_long: "badData",
  validation_error_post_users_must_be_an_array: "badData",
  validation_error_post_users_does_not_contain_1_required_value_s: "badData",
  validation_error_0_firstname_is_required: "badData",
  validation_error_0_lastname_is_required: "badData",
  validation_error_0_age_must_be_larger_than_or_equal_to_20: "badData",
  validation_error_0_age_must_be_less_than_or_equal_to_70: "badData",
  validation_error_put_users_id_must_be_of_type_object: "badData",
  validation_error_username_is_required: "badData",
  validation_error_username_must_be_a_string: "badData",
  validation_error_value_must_be_a_string: "badData",
  validation_error_value_must_be_an_array: "badData",
  validation_error_0_age_must_be_a_number: "badData",
};
